GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/5

###
DELETE http://localhost:3001/api/persons/5

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Omar Valenzuela",
    "number": "668-856-12-98"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "668-856-12-98"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Omar Valenzuela",
    "number": ""
}
